# Laraflare Master Nginx Configuration
worker_processes 1;
error_log logs/error.log;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 256M;

    server {
        listen 80 default_server;
        server_name localhost;
        root "{html}";
        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    {project_includes}
}
